DROP TABLE `EDU_SITE_CONFIG`, `EDU_SITES`, `EDU_USERS`;

CREATE TABLE IF NOT EXISTS `EDU_USERS` (
	`ID` VARCHAR(40)  COMMENT '用户唯一标志ID',
	`USER_NAME` VARCHAR(40) NOT NULL UNIQUE COMMENT '用户名，唯一， 不可以为空',
	`PASSWORD` VARCHAR(40) NOT NULL COMMENT '用户密码',
	`USER_ROLE` ENUM('ADMIN', 'TEACHER', 'STUDENT') NOT NULL DEFAULT 'ADMIN',
	`CREATE_TIME` DATETIME NOT NULL,
	`UPDATE_TIME` DATETIME NOT NULL, PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EDU_SITES` (
	`ID` VARCHAR(40)  COMMENT '站点唯一标志ID',
    `SITE_NAME` VARCHAR(40) NOT NULL UNIQUE COMMENT '站点的名称',
    `FULL_NAME` VARCHAR(100) NOT NULL UNIQUE COMMENT '站点的名称',
    `ADDRESS` VARCHAR(100) DEFAULT '' COMMENT '公司所在地址',
    `CREATE_TIME` DATETIME NOT NULL,
    `UPDATE_TIME` DATETIME NOT NULL, PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EDU_SITE_CONFIG` (
	`ID` VARCHAR(40)  COMMENT '站点唯一标志ID',
	`SITE_ID` VARCHAR(40),
	`ITEM_NAME` VARCHAR(40) NOT NULL COMMENT '站点配置项的名称',
	`ITEM_VALUE` VARCHAR(255) COMMENT '站点配置项的值',
	`CREATE_TIME` DATETIME NOT NULL,
	`UPDATE_TIME` DATETIME NOT NULL,
	PRIMARY KEY (`ID`),
    CONSTRAINT `EDU_SITE_CONFIG_FOREIGN_KEY_SITE_ID` FOREIGN KEY (`SITE_ID`) REFERENCES `EDU_SITES` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
